name: ChestShop
main: ChestShop\ChestShop
version: 2.0.0
api: [2.0.0]
load: POSTWORLD
author: Skyladd
description: Open your ChestShop
depend:
 - MassiveEconomy
permissions:
 chestshop:
  default: true
  description: "Allows using all the ChestShop things"
 chestshop.creative:
  default: op
  description: "Allows filling shops in creative mode"
